import type { Request, Response } from 'express';
import { KriteriaTipe } from '@prisma/client';
import { prisma } from '../config/prisma';
import { fail, success } from '../utils/api-response';

const parse = (body: Record<string, unknown>) => ({ kode: String(body.kode || '').trim().toUpperCase(), nama: String(body.nama || '').trim(), bobot: Number(body.bobot), tipe: String(body.tipe || '').toUpperCase() as KriteriaTipe, deskripsi: body.deskripsi ? String(body.deskripsi) : null, aktif: body.aktif === undefined ? undefined : Boolean(body.aktif) });
const valid = (x: ReturnType<typeof parse>) => x.kode && x.nama && Number.isFinite(x.bobot) && x.bobot > 0 && Object.values(KriteriaTipe).includes(x.tipe);
export async function listKriteria(_req: Request, res: Response) { return success(res, 'Kriteria berhasil diambil', { kriteria: await prisma.kriteria.findMany({ include: { subKriteria: { orderBy: { nilai: 'asc' } } }, orderBy: { kode: 'asc' } }) }); }
export async function createKriteria(req: Request, res: Response) { const data = parse(req.body); if (!valid(data)) return fail(res, 'Data kriteria tidak valid', 422); const kriteria = await prisma.kriteria.create({ data }); return success(res, 'Kriteria berhasil dibuat', { kriteria }, 201); }
export async function updateKriteria(req: Request, res: Response) { const current = await prisma.kriteria.findUnique({ where: { id: req.params.id } }); if (!current) return fail(res, 'Kriteria tidak ditemukan', 404); const data = { ...parse({ ...current, ...req.body }), aktif: req.body.aktif === undefined ? current.aktif : Boolean(req.body.aktif) }; if (!valid(data)) return fail(res, 'Data kriteria tidak valid', 422); const kriteria = await prisma.kriteria.update({ where: { id: current.id }, data }); return success(res, 'Kriteria berhasil diperbarui', { kriteria }); }
export async function deleteKriteria(req: Request, res: Response) { const current = await prisma.kriteria.findUnique({ where: { id: req.params.id } }); if (!current) return fail(res, 'Kriteria tidak ditemukan', 404); await prisma.kriteria.delete({ where: { id: current.id } }); return success(res, 'Kriteria berhasil dihapus'); }
export async function listSubKriteria(req: Request, res: Response) { const where = req.query.kriteriaId ? { kriteriaId: String(req.query.kriteriaId) } : {}; return success(res, 'Subkriteria berhasil diambil', { subKriteria: await prisma.subKriteria.findMany({ where, include: { kriteria: true }, orderBy: [{ kriteriaId: 'asc' }, { nilai: 'asc' }] }) }); }
export async function createSubKriteria(req: Request, res: Response) { const { kriteriaId, nama, nilai, keterangan } = req.body; if (!kriteriaId || !nama || !Number.isFinite(Number(nilai))) return fail(res, 'Data subkriteria tidak valid', 422); const subKriteria = await prisma.subKriteria.create({ data: { kriteriaId: String(kriteriaId), nama: String(nama), nilai: Number(nilai), keterangan: keterangan ? String(keterangan) : null } }); return success(res, 'Subkriteria berhasil dibuat', { subKriteria }, 201); }
export async function updateSubKriteria(req: Request, res: Response) { const current = await prisma.subKriteria.findUnique({ where: { id: req.params.id } }); if (!current) return fail(res, 'Subkriteria tidak ditemukan', 404); const { nama, nilai, keterangan } = req.body; if (!nama || !Number.isFinite(Number(nilai))) return fail(res, 'Data subkriteria tidak valid', 422); const subKriteria = await prisma.subKriteria.update({ where: { id: current.id }, data: { nama: String(nama), nilai: Number(nilai), keterangan: keterangan ? String(keterangan) : null } }); return success(res, 'Subkriteria berhasil diperbarui', { subKriteria }); }
export async function deleteSubKriteria(req: Request, res: Response) { await prisma.subKriteria.delete({ where: { id: req.params.id } }); return success(res, 'Subkriteria berhasil dihapus'); }
