import { Router } from 'express';
import { authorize, authenticate } from '../middleware/auth.middleware';
import { asyncHandler } from '../utils/async-handler';
import { deleteMustahik, getMustahik, getVerifikasi, listMustahik, listVerifikasi, submitVerifikasi, updateMustahik } from '../controllers/admin.controller';
import { createKriteria, createSubKriteria, deleteKriteria, deleteSubKriteria, listKriteria, listSubKriteria, updateKriteria, updateSubKriteria } from '../controllers/kriteria.controller';
import { getTopsisResult, getTopsisResults, processTopsis } from '../controllers/topsis.controller';
export const adminRouter = Router();
adminRouter.use(authenticate, authorize('ADMIN'));
adminRouter.get('/mustahik', asyncHandler(listMustahik));
adminRouter.get('/mustahik/:id', asyncHandler(getMustahik));
adminRouter.put('/mustahik/:id', asyncHandler(updateMustahik));
adminRouter.delete('/mustahik/:id', asyncHandler(deleteMustahik));
adminRouter.get('/verifikasi', asyncHandler(listVerifikasi));
adminRouter.get('/verifikasi/:id', asyncHandler(getVerifikasi));
adminRouter.post('/verifikasi/:id', asyncHandler(submitVerifikasi));
adminRouter.get('/kriteria', asyncHandler(listKriteria));
adminRouter.post('/kriteria', asyncHandler(createKriteria));
adminRouter.put('/kriteria/:id', asyncHandler(updateKriteria));
adminRouter.delete('/kriteria/:id', asyncHandler(deleteKriteria));
adminRouter.get('/subkriteria', asyncHandler(listSubKriteria));
adminRouter.post('/subkriteria', asyncHandler(createSubKriteria));
adminRouter.put('/subkriteria/:id', asyncHandler(updateSubKriteria));
adminRouter.delete('/subkriteria/:id', asyncHandler(deleteSubKriteria));
adminRouter.post('/topsis/process', asyncHandler(processTopsis));
adminRouter.get('/topsis/results', asyncHandler(getTopsisResults));
adminRouter.get('/topsis/results/:id', asyncHandler(getTopsisResult));
